/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as NotebooksNotebookIdRouteImport } from './routes/notebooks/$notebookId'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'
import { Route as ApiNotebooksClearTitleRouteImport } from './routes/api/notebooks/clear-title'
import { Route as ApiSourcesDeleteRouteImport } from './routes/api/sources/delete'
import { Route as ApiSourcesIngestRouteImport } from './routes/api/sources/ingest'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const NotebooksNotebookIdRoute = NotebooksNotebookIdRouteImport.update({
  id: '/notebooks/$notebookId',
  path: '/notebooks/$notebookId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotebooksClearTitleRoute = ApiNotebooksClearTitleRouteImport.update({
  id: '/api/notebooks/clear-title',
  path: '/api/notebooks/clear-title',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSourcesDeleteRoute = ApiSourcesDeleteRouteImport.update({
  id: '/api/sources/delete',
  path: '/api/sources/delete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSourcesIngestRoute = ApiSourcesIngestRouteImport.update({
  id: '/api/sources/ingest',
  path: '/api/sources/ingest',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/api/chat': typeof ApiChatRoute
  '/notebooks/$notebookId': typeof NotebooksNotebookIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/notebooks/clear-title': typeof ApiNotebooksClearTitleRoute
  '/api/sources/delete': typeof ApiSourcesDeleteRoute
  '/api/sources/ingest': typeof ApiSourcesIngestRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/api/chat': typeof ApiChatRoute
  '/notebooks/$notebookId': typeof NotebooksNotebookIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/notebooks/clear-title': typeof ApiNotebooksClearTitleRoute
  '/api/sources/delete': typeof ApiSourcesDeleteRoute
  '/api/sources/ingest': typeof ApiSourcesIngestRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/api/chat': typeof ApiChatRoute
  '/notebooks/$notebookId': typeof NotebooksNotebookIdRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
  '/api/notebooks/clear-title': typeof ApiNotebooksClearTitleRoute
  '/api/sources/delete': typeof ApiSourcesDeleteRoute
  '/api/sources/ingest': typeof ApiSourcesIngestRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/api/chat'
    | '/notebooks/$notebookId'
    | '/api/auth/$'
    | '/api/notebooks/clear-title'
    | '/api/sources/delete'
    | '/api/sources/ingest'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/api/chat'
    | '/notebooks/$notebookId'
    | '/api/auth/$'
    | '/api/notebooks/clear-title'
    | '/api/sources/delete'
    | '/api/sources/ingest'
  id:
    | '__root__'
    | '/'
    | '/sign-in'
    | '/api/chat'
    | '/notebooks/$notebookId'
    | '/api/auth/$'
    | '/api/notebooks/clear-title'
    | '/api/sources/delete'
    | '/api/sources/ingest'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignInRoute: typeof SignInRoute
  ApiChatRoute: typeof ApiChatRoute
  NotebooksNotebookIdRoute: typeof NotebooksNotebookIdRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
  ApiNotebooksClearTitleRoute: typeof ApiNotebooksClearTitleRoute
  ApiSourcesDeleteRoute: typeof ApiSourcesDeleteRoute
  ApiSourcesIngestRoute: typeof ApiSourcesIngestRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notebooks/$notebookId': {
      id: '/notebooks/$notebookId'
      path: '/notebooks/$notebookId'
      fullPath: '/notebooks/$notebookId'
      preLoaderRoute: typeof NotebooksNotebookIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notebooks/clear-title': {
      id: '/api/notebooks/clear-title'
      path: '/api/notebooks/clear-title'
      fullPath: '/api/notebooks/clear-title'
      preLoaderRoute: typeof ApiNotebooksClearTitleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sources/delete': {
      id: '/api/sources/delete'
      path: '/api/sources/delete'
      fullPath: '/api/sources/delete'
      preLoaderRoute: typeof ApiSourcesDeleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/sources/ingest': {
      id: '/api/sources/ingest'
      path: '/api/sources/ingest'
      fullPath: '/api/sources/ingest'
      preLoaderRoute: typeof ApiSourcesIngestRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignInRoute: SignInRoute,
  ApiChatRoute: ApiChatRoute,
  NotebooksNotebookIdRoute: NotebooksNotebookIdRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
  ApiNotebooksClearTitleRoute: ApiNotebooksClearTitleRoute,
  ApiSourcesDeleteRoute: ApiSourcesDeleteRoute,
  ApiSourcesIngestRoute: ApiSourcesIngestRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
